homepage: "https://turbovnc.org/"
language: c
primary_contact: "azesinte@gmail.com" 
auto_ccs:
  - "security@turbovnc.org"
main_repo: "https://github.com/TurboVNC/turbovnc.git"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - centipede
