homepage: "https://nghttp2.org/nghttp3/"
language: c
primary_contact: "tatsuhiro.t@gmail.com"
auto_ccs:
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/ngtcp2/nghttp3.git'
